### ISSUE TITLE
Replace excel files with outlook data

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#103]
Blocked, waiting for data files

**Comment by cypressf** [comment]
default outlook data is in dropbox now https://www.dropbox.com/s/tp5r1on9fbudka9/ParisForever_Covid19_outlook.xls?dl=0

- [x] test to make sure it has all the data it needs to display in the dashboard
- [x] get any errors fixed
- [x] add it to the dashboard
- [x] add updated paris2c
- [ ] add updated paris1.5c depending on if we want it (blocked)

**Comment by cypressf** [comment]
These are the issues I noticed when looking at the data:

![Screen Shot 2021-03-16 at 13 31 25](https://user-images.githubusercontent.com/443397/111353699-ee1dac00-865b-11eb-83dc-b47f62e61073.png)
![Screen Shot 2021-03-16 at 13 30 08](https://user-images.githubusercontent.com/443397/111353705-ef4ed900-865b-11eb-8825-2fdc44e8c365.png)
![Screen Shot 2021-03-16 at 13 28 54](https://user-images.githubusercontent.com/443397/111353708-efe76f80-865b-11eb-85bf-ce5d42d5145c.png)
![Screen Shot 2021-03-16 at 13 28 39](https://user-images.githubusercontent.com/443397/111353712-f0800600-865b-11eb-9ac1-85aaf2581348.png)

**Comment by cypressf** [comment]
@holak updated the [ParisForever file](https://www.dropbox.com/s/tp5r1on9fbudka9/ParisForever_Covid19_outlook.xls?dl=0) to fix all the above issues and I committed it to the repo https://github.com/cypressf/EPPADashboard/commit/b38a40b3615405b50da98d438c43de3acfa66f32. It is deployed to https://mitjointprogram.shinyapps.io/outlook2021/ now.

**Comment by cypressf** [comment]
@holak do I need to add an updated version of Paris2C and Paris1.5C as well?

**Comment by holak** [comment]
@cypressf yes, I will send you updated versions of the other scenarios when I have them. I wanted to make sure the reporting was all set before running those. Thanks

**Comment by holak** [comment]
@cypressf I found 2 issues with the ParisForever scenario: (1) Sectoral CO2-equivalant Emissions was missing the "Other Manufacturing" category (due to a typo), and (2) the Air Pollutant Emissions breakdown colors were not in the Outlook color scheme. An updated ParisForever file that addresses these issues is now in the dropbox.

I will get you the other scenarios next.

**Comment by holak** [comment]
@cypressf I have now added the new Paris2C_outlook excel file to the dropbox. I'm waiting on Sergey and Henry to decide if they also want Paris1.5C or any other scenarios. For now, please upload the latest ParisForever and Paris2C files. Thanks!

**Comment by cypressf** [comment]
@holak I added the corrected ParisForever file and the latest Paris2C file.
