### ISSUE TITLE
Try mapping overlay of roads

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#106]
Visual overlay available on every tab

**Comment by cypressf** [comment]
The [roads shape file](https://github.com/cypressf/climate-map-tests/blob/main/mit%20data/Hwy/Hwy.shp) is too large to conveniently load in a web app right now. Even after reducing the size [using tricks](https://github.com/cypressf/climate-map-tests/commit/2233bd472036db19aa69398b5b69703585f33886) like stripping out all the metadata and converting to a topo file, it's still 17 MB, 25x larger than the US county map.

We may need to start with a less high-resolution road file.

**Comment by cypressf** [comment]
I'm having another issue with it—it's not lining up with the county map after using the same albers projection for both of them. I wonder if I made a mistake when converting them from shape file to geojson, or if the difference also exists in the original shape file.

![Screen Shot 2021-02-26 at 15 12 38](https://user-images.githubusercontent.com/443397/109350175-11b3ba80-7845-11eb-86d4-c16968b7d4a8.png)

**Comment by cypressf** [comment]
Since the map is too large to load quickly on the website, I'm looking for alternative less-detailed road maps. When I find one I'll test to see if it still has the same mismatched projection issue. If so, I'll look into it, if not, great—no need to debug now.

**Comment by cypressf** [comment]
Some examples of lower res data:

https://gist.github.com/bricedev/96d2113bd29f60780223
https://observablehq.com/@floledermann/drawing-maps-from-geodata-in-d3-condensed-version
https://github.com/jgoodall/us-maps/tree/master/topojson-simplified

one got its road data from here https://www.naturalearthdata.com/features/. maybe we can get road data from there as well and simplify to topojson

**Comment by cypressf** [comment]
While I was researching roads I read a little about the [Commodity Flow Survey](https://www.census.gov/programs-surveys/cfs.html), which the census says is the most detailed publicly available data on transportation of goods in the US. They have flow of goods from certain commodity areas, which are groupings of counties in metro areas. We could potentially map these on our county map along a visualization of flow between the areas.

![Screen Shot 2021-02-26 at 15 33 03](https://user-images.githubusercontent.com/443397/109352254-83d9ce80-7848-11eb-9aab-dc4b6404f4a2.png)
![Screen Shot 2021-02-26 at 15 33 27](https://user-images.githubusercontent.com/443397/109352264-85a39200-7848-11eb-940d-61558629fdef.png)

**Comment by cypressf** [comment]
This is the source of the lower res road data in the gist linked [above](https://github.com/cypressf/mit-climate-data-viz/issues/106#issuecomment-786878743):

[natural earth data: roads](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/roads/)

side note: they also have

- [seaports](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/ports/),
- [airports](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/airports/),
- and [railroads](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/railroads/)

**Comment by cypressf** [comment]
I tried filtering the natural earth world roads data to just the usa, projecting it with albers, and plotted it on top of our counties. 
![Screen Shot 2021-02-26 at 16 18 47](https://user-images.githubusercontent.com/443397/109356204-60b21d80-784e-11eb-803c-ba99359b81e3.png)

It's also offset! I think the projection doesn't line things up like I expect.

**Comment by cypressf** [comment]
The good news is this new file is only 1.7MB, and that's still with some metadata like road name and type. I think the size concern is mostly fixed. I just need to focus on getting the projection correct.

**Comment by azzacasch** [comment]
Hey Cypress,

Thanks for the update - this looks to be just the right level of detail with the roadways to start as a visual overlay and glad the file size shouldn't be an elephant!  The projection is always the stinker with these things.

Have a great weekend,
Adam

C. Adam Schlosser
Senior Research Scientist, Center for Global Change Science
Deputy Director, MIT Joint Program on Science and Policy of Global Change
http://globalchange.mit.edu

50 Ames St.
Building E19-439L
Massachusetts Institute of Technology
Cambridge, MA 02139-4307

Phone: +1-617-253-3983
Fax: +1-617-253-9845
casch@mit.edu

**Comment by azzacasch** [comment]
Hey Cypress,

Just a quick response - this bit looks really promising!  Looks to be the sort of thing we were talking about in terms of how to we somehow create a transportation “risk” metric so that it can be combined in our entry-level page. 

I think I may have missed this when you originally sent it.  I just discovered today that I’ve had some pathologic problem with my email (syncing to my laptop) and the only way I could really troubleshoot the problem was to remove my MIT Exchange account from my laptop and completely rebuild my inbox today.  Arrrgh...

—a

C. Adam Schlosser
Senior Research Scientist, Center for Global Change Science
Deputy Director, MIT Joint Program on Science and Policy of Global Change
http://globalchange.mit.edu

50 Ames St.
Building E19-439L
Massachusetts Institute of Technology
Cambridge, MA 02139-4307

Phone: +1-617-253-3983
Fax: +1-617-253-9845
casch@mit.edu

**Comment by cypressf** [comment]
Ah ha! I figured out the issue. I forgot I had used an alternate, much [more lightweight county map](https://observablehq.com/@d3/u-s-map)—not the one Alyssa originally provided me with. That county map used a slightly different projection than the one I was using to convert Alyssa's shape file to geojson. My head-banging is over.

`d3.geoAlbersUsa().scale(1300).translate([487.5, 305])` instead of `d3.geoAlbersUsa().fitSize([975, 610], d)`

![A nicely overlapping projection of roads onto the map](https://user-images.githubusercontent.com/443397/109878472-56bf5e80-7c42-11eb-85d5-49d9c81ce628.png)

**Comment by cypressf** [comment]
Examples with data overlays:
![Screen Shot 2021-03-03 at 17 34 55](https://user-images.githubusercontent.com/443397/109881739-c9323d80-7c46-11eb-956a-d17319462992.png)
![Screen Shot 2021-03-03 at 17 33 47](https://user-images.githubusercontent.com/443397/109881740-c9cad400-7c46-11eb-8d3c-c7374e853329.png)

**Comment by cypressf** [comment]
Done in https://github.com/cypressf/climate-risk-map/commit/8b0a15cfaea7782ddeeccb301f77cf692e467437

**Comment by azzacasch** [comment]
Cool beans Cypress!

—a

C. Adam Schlosser
Senior Research Scientist, Center for Global Change Science
Deputy Director, MIT Joint Program on Science and Policy of Global Change
http://globalchange.mit.edu

50 Ames St.
Building E19-439L
Massachusetts Institute of Technology
Cambridge, MA 02139-4307

Phone: +1-617-253-3983
Fax: +1-617-253-9845
casch@mit.edu
