### ISSUE TITLE
Use different sector categories for sectoral co2 emissions

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#113]
https://github.com/cypressf/mit-climate-data-viz/issues/110
> Sectoral CO2eq Emissions: I updated the model code for sectoral emissions to use different sector categories. To have these appear correctly on the dashboards, I need to rerun the scenarios to report the correct new categories (in addition to adding color mapping, and adding it to the query list in the outlook excel files)

- [x] add latest excel file to eppa dashboard reference and test to ensure it works
- [x] get updated sectoral co2 emissions excel files for all scenarios
- [x] add latest excel file to other scenarios

**Comment by cypressf** [comment]
![Screen Shot 2021-03-01 at 11 43 28](https://user-images.githubusercontent.com/443397/109529073-57f65d00-7a83-11eb-9b16-9e30846fe7d0.png)

@holak does this look right?

**Comment by cypressf** [comment]
blocked (need latest excel files for all scenarios)

**Comment by holak** [comment]
Yes!

**Comment by holak** [comment]
I added updated excel files for the other scenarios with the fix for sectoral CO2 emissions to the dropbox (in the EPPA and Outlook subfolders).
