### ISSUE TITLE
Create two separate tabs for "economic data" and "climate data"

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#138]

**Comment by cypressf** [comment]
Should we call these "economic data" and "climate data" or "energy and economics" and "emissions and climate"?

**Comment by holak** [comment]
Let's do "energy and economics" and "emissions and climate"

**Comment by holak** [comment]
@cypressf I am having an issue that when I add regional climate data to the excel, I exceed the row limit of the excel file. I'm thinking one solution is to create two separate data tabs: "data_econ" and "data_clim" and have the relevant variables reported in each. You then may not need the column in the query tab that assigns variables to "Econ" or "Climate". Let me know your thoughts, or any other ideas.

**Comment by holak** [comment]
@cypressf let me know how you think I should proceed on this

**Comment by cypressf** [comment]
Separate tabs sounds good to me! (@holak)
