### ISSUE TITLE
Limit price data to years 2020-2050

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#139]
Report all variables in "Economic data" category only for 2015-2050, except for price data, which we will be reported for 2020-2050 (Alternatively, we can visualize all variables for 2020-2050).

**Comment by holak** [comment]
@cypressf I have updated the model reporting so the excel files only have 2020-2050 for all data that will go under the "Energy and Economic Results" dropdown. So this is done.

**Comment by cypressf** [comment]
I'll need to update all the excel files for all scenarios, not just ParisForever
