### ISSUE TITLE
Rename breakdown dropdowns to "source", "eppa region", "regional group"

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#140]

**Comment by cypressf** [comment]
I'm going to ask @holak to see if these can be renamed in the excel file

**Comment by holak** [comment]
@cypressf I'm not sure what you mean. The breakdowns are not currently named in the excel file (there are no column headings... and they are a pain to add). Do you want me to add a new tab to the excel with these names?

**Comment by cypressf** [comment]
@holak you're so right. My mistake! I forgot how the breakdown names were specified in the code.

**Comment by holak** [comment]
When choose breakdown by "Source", the legend title for the figure still says "Sector" --> Change to "Source"
When choose breakdown by "EPPA Region", the legend title for the figure still says "region"--> Change to "EPPA Region"
(When choose breakdown by "Regional Group", the legend title for the figure correctly says "Regional Group").

**Comment by cypressf** [comment]
Good QA! I'll fix that. Currently I'm running into an issue using names with spaces in them, due to https://stackoverflow.com/questions/29133567/using-ggplot2-with-columns-that-have-spaces-in-their-names

I will find a workaround by mapping the names with spaces to names without spaces, and finding a way to set the legend label independently of the data column name

**Comment by cypressf** [comment]
It looks like I can work around the column name limitation by quoting it in backticks instead of quotation marks (`` `EPPA Region` `` instead of `"EPPA Region"`).

The error occurs inside `ggplot`

```
Warning: Error in parse: <text>:1:6: unexpected symbol
1: EPPA Region
         ^
  182: parse
  180: FUN
  179: lapply
  178: map
  177: chr_parse_exprs
  176: parse_exprs
  175: parse_expr
  174: FUN
  173: lapply
  172: aes_string
  169: plotTime [/Users/cypressf/Desktop/mit project/GCAM-dashboard/R/server-helpers.R#498]
  168: getTimePlot [/Users/cypressf/Desktop/mit project/GCAM-dashboard/inst/app/server.R#178]
  167: renderPlot [/Users/cypressf/Desktop/mit project/GCAM-dashboard/inst/app/server.R#186]
  165: func
  125: drawPlot
  111: <reactive:plotObj>
   95: drawReactive
   82: origRenderFunc
   81: output$timePlot
    1: runApp
```

in `plotTime()` when `subcatvar == "EPPA Region"` the `ggplot` errors out, but when ``subcatvar == `EPPA Region` `` it works
