### ISSUE TITLE
Separate "air pollutant" variables into individual pollutants

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#142]
We need to separate "Air pollutant" emissions reporting into reporting by individual pollutant, i.e., ammonia emissions, black carbon emissions, etc. (Jen, I don't think it makes sense to combine their reporting. What are you thoughts on this?).

**Comment by holak** [comment]
@cypressf I tried to separate air pollutants, but something is off (the dashboard gives an error), so I need to fix something

**Comment by cypressf** [comment]
Right! I debugged it and I see we need to add the different air pollutant emissions to the query tab.

**Comment by holak** [comment]
Thanks! I'll add each air pollutant to the query tab
