### ISSUE TITLE
Rename "CO2-eq emissions" to "CO2-eq GHG Emissions"

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#144]

**Comment by holak** [comment]
@cypressf I changed the variable name in the excel reporting. It already has reporting by source (individual GHG), so I'm not sure what Sergey meant by that

**Comment by cypressf** [comment]
Cool, I removed the task to break it down by source since we're already doing that. In terms of the excel file, I think we need to update the other scenarios too.
