### ISSUE TITLE
Rename "Europe-EUplus" to "Europe"

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#146]

**Comment by holak** [comment]
@cypressf done (in excel reporting)

**Comment by cypressf** [comment]
The data tab still has Europe-EUplus in the region column

**Comment by holak** [comment]
Ahh thanks, there is one other place in my code I forgot to change it to "Europe". I'll do that

**Comment by cypressf** [comment]
Updated Paris_Forever now has Europe in the region column. Waiting on the updated Paris2C and Paris1.5C to close this issue.
