### ISSUE TITLE
Show waterway tonnages, and dropdown for industry

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#153]
- [x] show tonnages
- [x] add industry dropdown
- [x] change tonnages and color depending on industry

**Comment by cypressf** [comment]
![2021-04-08 22 45 31](https://user-images.githubusercontent.com/443397/114121339-35463800-98bc-11eb-8625-018aa6deea98.gif)

done in https://github.com/cypressf/climate-risk-map/commit/d74462c2d39d0f014a3eab8e0d63818e159d42d5

**Comment by azzacasch** [comment]
Cypress,

I like it!

—a

C. Adam Schlosser
Senior Research Scientist, Center for Global Change Science
Deputy Director, MIT Joint Program on Science and Policy of Global Change
http://globalchange.mit.edu

50 Ames St.
Building E19-439L
Massachusetts Institute of Technology
Cambridge, MA 02139-4307

Phone: +1-617-253-3983
Fax: +1-617-253-9845
***@***.***
