### ISSUE TITLE
Attribution footer for my repo and link to GCAM github

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#166]
Code available here
Benefited from this repo

**Comment by cypressf** [comment]
Done in https://github.com/cypressf/EPPADashboard/commit/5130d52142f66777898283910acc88560f07b4d2

**Comment by holak** [comment]
@cypressf in your repo (https://github.com/cypressf/EPPADashboard/tree/climate-outlook) could you update the first sentence of the README to say: "The EPPA Dashboard is a scenario explorer for the MIT Economic Projection and Policy Analysis (EPPA) model."

**Comment by cypressf** [comment]
yup! Done
