### ISSUE TITLE
Hover over graphs to see values

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#18]
- [x] Port over functionality from GCAM-LAC
- [x] Make it work with line graphs
- [x] Resolve flickering glitch
- [x] Resolve issue where box hovers off on the right and below mouse https://github.com/cypressf/EPPADashboard/commit/823cfcfc85cff4952bc8f58dd3f8ec8e0a9bceb7

**Comment by cypressf** [comment]
Note: GCAM-LAC has this

**Comment by cypressf** [comment]
I started porting the GCAM-LAC code into my code. I need to access the data of the current plot in the hover code, which I can do with the getPlotData() function. I'll pull out the call to it from plotTime(), and save the value in server.R so I can put it in timePlot.df

**Comment by cypressf** [comment]
I ported over the code that shows hover values. It has a small glitch where it flickers while moving the mouse vertically that I will investigate, but it works.

**Comment by holak** [comment]
![image](https://user-images.githubusercontent.com/12715920/107699196-bbab1880-6c83-11eb-84c5-02bacb8981de.png)

**Comment by cypressf** [comment]
Broken in firefox and chrome for jennifer on old and new laptop and desktop (running windows). I'll try it in windows

**Comment by cypressf** [comment]
On my Windows 10 laptop, in both chrome Version 89.0.4389.90 (Official Build) (64-bit) and firefox 86.0.1 (64-bit) the tooltip value [displays correctly](https://user-images.githubusercontent.com/443397/111358495-c54be580-8660-11eb-8f7d-2de943a121bb.mp4) next to the mouse cursor.

**Comment by cypressf** [comment]
Oh my god! I thought I was never going to reproduce this but it randomly happened to me when I woke up my laptop from sleep after unplugging it from a monitor. This is on macOS 10.15.7, Firefox 86.0.1 (64-bit).

![2021-03-16 19 42 11](https://user-images.githubusercontent.com/443397/111393887-00194200-8690-11eb-9666-c72efe02503d.gif)

I'm guessing this has to do with multi-monitor setups. @holak do you use multiple monitors, or a laptop plugged into a monitor? I'm going to debug as much as I can while this bug is still reproducible on my computer. I feel like if I do the wrong thing it'll go back to working normally and I'll have missed my chance.

**Comment by cypressf** [comment]
I'm seeing the same bug in the GCAM-LAC dashboard. I copied my code from that dashboard, so the bug was in the original implementation.
![2021-03-16 19 59 20](https://user-images.githubusercontent.com/443397/111395063-5b4c3400-8692-11eb-9e82-2503afd7b8d7.gif)

**Comment by holak** [comment]
@cypressf At least you see it now too! I do NOT use multiple monitors or plug my laptop into a monitor, so that is not the problem for me.

**Comment by cypressf** [comment]
I investigated more with display settings.

- When I use laptop display, not plugged into a monitor I see the offset-tooltip bug
- When I use monitor, in "mirror display mode", the tooltip tracks the cursor correctly
- When I use my monitor in "extend display mode", the tooltip tracks the cursor correctly on my monitor, but not on my laptop display
- When I use my monitor scaled to a different resolution than the default, I see the bug (the offset is the same, regardless of the resolution I scale it to)

**Comment by cypressf** [comment]
Debugging hover offset: the percentage from each side of the image is correct. The bug is between calculating percentage, and displaying the hover tooltip
