### ISSUE TITLE
Add critical habitat data

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#197]
To add to environment tab add as county-level data (% of area?). Exclude river habitat from this calculation. Also add to risk metrics tab.

Waiting on data for this.

**Comment by cypressf** [comment]
Alyssa says:

> I have uploaded a new climate.csv file to the dropbox. The new, last column PerCritHab is the percent of a county that contains critical habitat. 
> I also added the following to our 'Notes on Indicators' Doc
> Critical Habitat
> Source: https://ecos.fws.gov/ecp/report/critical-habitat
> The data we are providing is the percent of land in a county that is considered critical habitat according to the USFWS Threatened & Endangered Species Active Critical Habitat Report.

**Comment by cypressf** [comment]
Adam also mentioned that we could calculate overlaps of critical habitat areas with densely human-populated areas.

**Comment by cypressf** [comment]
Add to risk metrics as well

**Comment by cypressf** [comment]
The distribution is kinda weird, but here it is
<img width="1340" alt="Screen Shot 2021-09-10 at 11 47 41" src="https://user-images.githubusercontent.com/443397/132881297-c6eb37d8-9b94-4009-b3db-8c3e33271b6f.png">

**Comment by cypressf** [comment]
Here it is in risk metrics. Unfortunately, due to the distribution (the bottom 85% of counties have no critical habitat), everything is at least in the 85th percentile. I'm thinking of excluding it from risk metrics for now, and figuring out to do at our next thursday meeting.
<img width="1170" alt="Screen Shot 2021-09-10 at 11 49 04" src="https://user-images.githubusercontent.com/443397/132881518-bad90c72-4d85-4237-9ce7-222eb60cca34.png">

I realize this is unintuitive. The only time it happens is when many many counties have the exact same value (in this case, 0). If all the counties had some low values that were not equal to each other, they would be assigned percentiles ranging from 0 to 85, but since they all share a value, they cannot be ordered, and are thus all clumped into the same percentile

**Comment by azzacasch** [comment]
Hey Cypress,

Thanks!  Sounds good to remove as a combined metric/data for now.  I had one knee-jerk idea but when I thought more about it - I don’t think it’ll work.  So yup - let’s hold off for now.

—a

C. Adam Schlosser
Senior Research Scientist, Center for Global Change Science
Deputy Director, MIT Joint Program on Science and Policy of Global Change
http://globalchange.mit.edu

50 Ames St.
Building E19-439L
Massachusetts Institute of Technology
Cambridge, MA 02139-4307

Phone: +1-617-253-3983
Fax: +1-617-253-9845
***@***.***
