### ISSUE TITLE
Add energy expenditure share to risk metrics.

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#202]

**Comment by cypressf** [comment]
![Screen Shot 2021-09-08 at 19 43 22](https://user-images.githubusercontent.com/443397/132599692-25429071-35f3-4ffc-8a72-9d3a85350991.png)

**Comment by cypressf** [comment]
![Screen Shot 2021-09-08 at 19 43 37](https://user-images.githubusercontent.com/443397/132599707-5dda81eb-dd57-4c88-99f2-4fa6f4dd7210.png)

**Comment by azzacasch** [comment]
Hey Cypress,

This looks great - I know that it’s at state level, but this is something the platform will need to be able to contend with when we bring in our projections of the socio-economics (which can only be provided at the state level - at best).

Great work!
Adam

**Comment by cypressf** [comment]
Thanks! I'm glad it'll be useful for the projections as well.
