### ISSUE TITLE
make editor (to allow researchers to edit visualizations)

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#217]
# Authentication

- [x] Research best way to implement authentication
- [x] Implement authentication to protect database
- [x] Deploy

# Editor history

- [ ] Research to identify the best way to save editor history
- [ ] Implement editing history

# Write capabilities

- [x] Add database write capabilities

# Frontend UI

- [x] Authentication page
- [x] Editor for map visualizations
- [x] Editor for tabs
- [ ] Editor for order of visualizations

**Comment by cypressf** [comment]
# Update: prototype working

I have a minimal prototype editor for map visualizations:

![2021-10-01 12 35 13](https://user-images.githubusercontent.com/443397/135656641-1d836933-8dec-4a46-9890-e2329a6fc13c.gif)

Still todo:

- Authentication
- Drafts, so you don't publish changes to the website immediately upon testing out a new color
- Bug fixes
- Deploying to svante

**Comment by azzacasch** [comment]
Looks awesome Cypress!

—a


C. Adam Schlosser
Senior Research Scientist, Center for Global Change Science
Deputy Director, MIT Joint Program on Science and Policy of Global Change
http://globalchange.mit.edu

50 Ames St.
Building E19-439L
Massachusetts Institute of Technology
Cambridge, MA 02139-4307

Phone: +1-617-253-3983
Fax: +1-617-253-9845
***@***.***

**Comment by cypressf** [comment]
# Frontend UI

## Data visualization

- [x] Map Type
- [x] Color Scale
- [x] Color Palette
- [x] Invert
- [x] Show Probability Density
- [x] Formatter Type
- [x] Decimal Places
- [x] Legend tick count
- [ ] Legend decimal places
- [x] Legend Formatter Type
- [ ] Dataset
- [ ] Should Normalize
- [ ] Default Date Range
- [ ] Default Data Source
- [x] Name
- [ ] Subcategory

## Dataset

- [x] name
- [x] short_name
- [x] description
- [x] units

**Comment by cypressf** [comment]
There's a bug with color palette selection. Only certain color palettes are available for the threshold scale type, and only certain colors are available for the other types. I need to associate color palettes with scale types in the database, and only allow setting them to the color palettes available for that scale type.

**Comment by cypressf** [comment]
Because we're going to get this on svante4 soon, I've started looking at authentication solutions. https://github.com/ramosbugs/openidconnect-rs is a possibility.

**Comment by cypressf** [comment]
To view the editor at `/editor` I need to [configure apache to support `react-router-dom`](https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing).

I tried configuring apache to support react-router-dom but the [.htaccess file](https://github.com/cypressf/climate-risk-map/commit/5d1b78ea4c29c7231c8ffb541fbdada0e8435a89) doesn't seem to be making a difference. svante3.mit.edu/editor doesn't show the editor UI. @mjbludwig could I get an assist here? Is there a way to test that apache is obeying the .htaccess rules I added?

**Comment by cypressf** [comment]
I tried configuring apache to support react-router-dom but the .htaccess file didn't get copied from `public` into `build` when I ran `yarn build`. I will check to see if there's a config option for that with `vite`, since I'm not using the more standard `webpack`.

**Comment by cypressf** [comment]
It looks like we could change the VirtualHost configuration instead of using an .htaccess file: https://stackoverflow.com/a/48872476/382892. @mjbludwig would this virtualhost configuration be relatively straightforward to change?

**Comment by cypressf** [comment]
@mjbludwig made some progress on the server config today, and it worked! the editor was visible to the internet on svante3. he'll refine that a bit, and then deploy to svante3 and 4.

**Comment by cypressf** [comment]
# Color Palette bug

I need to make a mapping from threshold schemes to color palettes and from interpolators to color palettes so I can grab all color palettes that are interpolatable, or all color palettes that are threshold-able. from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-scale-chromatic/v2/index.d.ts

## Schemes

### Continuous

I think continuous schemes are arrays indexed 3 to 9, each containing an array with the # of colors corresponding to its index.

```
BrBG
PRGn
PiYG
PuOr
RdBu
RdGy
RdYlBu
RdYlGn
Spectral
Blues
Greens
Greys
Oranges
Purples
Reds
BuGn
BuPu
GnBu
OrRd
PuBuGn
PuBu
PuRd
RdPu
YlGnBu
YlGn
YlOrBr
YlOrRd
```

### Categorical

Categorical schemes are arrays of colors. Each can be a different length.

```
Category10
Accent
Dark2
Paired
Pastel1
Pastel2
Set1
Set2
Set3
Tableau10
```


## Interpolators

```
BrBG
PRGn
PiYG
PuOr
RdBu
RdGy
RdYlBu
RdYlGn
Spectral
Blues
Greens
Greys
Oranges
Purples
Reds
Turbo
Viridis
Inferno
Magma
Plasma
Cividis
Warm
Cool
Rainbow
Sinebow
CubehelixDefault
BuGn
BuPu
GnBu
OrRd
PuBuGn
PuBu
PuRd
RdPu
YlGnBu
YlGn
YlOrBr
YlOrRd
```

**Comment by cypressf** [comment]
working on color scheme bug on branch `editor-bugs`

**Comment by cypressf** [comment]
[`/editor`](http://svante3.mit.edu/editor) is exposed on development and prod now. it still buggy, and not recommended to use on prod because it could possibly break things, but it exists.

**Comment by cypressf** [comment]
I can prevent the wrong color from being selected when in a specific scale type, but if someone switches between scale types, the issue is we also need to switch the color scheme to something appropriate for that scale type if it's not already.

color scheme: YlOrRd
scale type: interpolator

switch scale type to: threshold
*breaks because YlOrRd is not valid for threshold*

I added code to switch the color scheme to the first valid color scheme for the newly chosen scale type on the backend, but we also need code to do so on the frontend because we mutate the frontend state while awaiting confirmation that the backend state change went through.

**Comment by cypressf** [comment]
# Colors bug

not all color schemes are the same type. categorical schemes behave differently than continuous schemes.

`scales.schemeBlues` is an array with indices 3 to 9 containing arrays of increasing number of colors.
`scales.schemeSet1` is an array from 0 to 8 containing color strings.

Not all categorical color schemes have the same number of colors. https://observablehq.com/@d3/color-schemes
I'm unsure if continuous schemes have the same min and max number of divisions.

**Comment by cypressf** [comment]
# Colors bug

For now I'll disable threshold color schemes, and only use interpolators, since threshold color schemes have different limitations on the scale domain (e.g., at least 3 domain values, or at a maximum 9 for threshold schemes based on continuous colors, or an arbitrary maximum number of domain values for categorical colors).

In the future, in order to allow people to choose an arbitrary color scheme, there will need to be a system that identifies enforces domain constraints for each color scheme. Those constraints would likely be in the backend.

It could be easier to instead have a number of arbitrary preset discrete color schemes on the frontend, and then store them as color/domain pairs in the database, instead of storing the name of the color scheme and then determining if the domain matches up with the limits on the frontend.

**Comment by cypressf** [comment]
# Apache config bug on svante4

  @mjbludwig I'm trying to use the editor on svante4, but it's not forwarding the requests to the editor service. I can tell that it's not forwarding requests because I'm not seeing any request logs for `PATCH` requests in `podman logs crm_backend |& grep PATCH`. I do see `PATCH` request logs on svante3. I compared the `/etc/httpd/conf.d/climate_risk_map.conf` on svante3 and svante4 to see if any obvious obvious differences stood out to me, but I couldn't spot anything. Could you take a look at the configs to see what might be happening on svante4 to prevent it from successfully forwarding requests? Perhaps the PAM had different credentials?


I can successfully mutate the state by sshing in and running


```sh
curl -v --request PATCH --url http://localhost:8002/map-visualization --header 'Content-Type: application/json' --data "@/opt/crm_home_dir/temp.json"
```

Where [`temp.json`](https://gist.github.com/cypressf/594dcd0a30d97efa57580a5049ca8f2d) contains a mutation to rename `Water Stress` to `Water Stress Test`.

**Comment by cypressf** [comment]
Morgan fixed the apache issue on svante4 so it's now possible to edit! https://est.mit.edu/editor

Be careful. Any edits made appear live on the website immediately.

**Comment by cypressf** [comment]
I'm working on adding the ability to change the dataset associated with a map visualization on the `map-viz-creator` branch. This is useful if, for example, we get a newer version of that data and upload it.

**Comment by cypressf** [comment]
Now you can edit datasets and data sources:

https://est.mit.edu/dataset-editor
https://est.mit.edu/data-source-editor
