### ISSUE TITLE
Make histogram more readable for long-tailed distributions

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#84]
Sometimes the color is close to white for most of the distribution, because of the map color scheme.
Consider

- Using black bars or lines instead of color-scheme coded ones. You could put the colors below the x-axis to correlate with them.
- Maybe consider adding a grey background if the color bars are almost white
- Consider binning the long tails into a >x bin
- Consider hiding long-tailed distributions, but having placeholder text to indicate why we hid it

**Comment by cypressf** [comment]
I'm going to try replacing the histogram with a KDE line graph above the color scale legend, something like this:

![IMG_0439](https://user-images.githubusercontent.com/443397/107806291-a0e4ac80-6d34-11eb-9b2f-6f65e0183e4c.jpeg)

**Comment by azzacasch** [comment]
Hey Cypress,

OK - I’d be curious to see how that looks.  I know of like the way we have it now - but I can see the point that it’s hard to see it with histograms that have fat tails.

I have one request - can you put at the top of your list to recalculate the weighting on the risk metric page?

Thanks!
Adam

C. Adam Schlosser
Senior Research Scientist, Center for Global Change Science
Deputy Director, MIT Joint Program on Science and Policy of Global Change
http://globalchange.mit.edu

50 Ames St.
Building E19-439L
Massachusetts Institute of Technology
Cambridge, MA 02139-4307

Phone: +1-617-253-3983
Fax: +1-617-253-9845
casch@mit.edu

**Comment by azzacasch** [comment]
Oops - just read my email, I meant to say

“I kind of like the way we have it now…”

—a

C. Adam Schlosser
Senior Research Scientist, Center for Global Change Science
Deputy Director, MIT Joint Program on Science and Policy of Global Change
http://globalchange.mit.edu

50 Ames St.
Building E19-439L
Massachusetts Institute of Technology
Cambridge, MA 02139-4307

Phone: +1-617-253-3983
Fax: +1-617-253-9845
casch@mit.edu

**Comment by cypressf** [comment]
Whoops, I missed these comments. I will enable github notifications so I can see them in the future. I got your separate email though and fixed the normalization weighting.

**Comment by cypressf** [comment]
- [x] extract legend to component
- [x] fix issue with legend component when no data is selected with multi-data-selector

```
TypeError: selections[0] is undefined
getColorScheme
src/MapUI.tsx:334

  331 | }
  332 | 
  333 | const getColorScheme = (selectedDataDefinitions: DataDefinition[], selections: DataIdParams[]) => {
> 334 |     const normalization = selections[0].normalization;
  335 |     switch (normalization) {
  336 |         case Normalization.Raw: return selectedDataDefinitions[0].color;
  337 |         case Normalization.Percentile: return percentileColorScheme;

MapUI
src/MapUI.tsx:159

  156 | }
  157 | 
  158 | const selectedDataDefinitions = getDataDefinitions(selections);
> 159 | const color = getColorScheme(selectedDataDefinitions, selections);
      | ^  160 | const legendFormatter = getLegendFormatter(selectedDataDefinitions, selections);
  161 | const ticks = getLegendTicks(selectedDataDefinitions, selections);
  162 | const title = getTitle(selectedDataDefinitions, selections);
```
